import pymupdf
import re

doc = pymupdf.open(r'E:\需求记录\文档资料\Books\mml-book_printed.pdf')

index_items = []
for pno in range(412, 417):
    page = doc[pno]
    text = page.get_text()
    for line in text.splitlines():
        line = line.strip()
        if not line or line in ['Index'] or re.match(r'^\d+$', line):
            continue
        if 'Draft (' in line or 'To be published by Cambridge' in line or 'https://mml-book.com' in line or 'c⃝' in line:
            continue
        m = re.match(r'^(.*?),\s*([\d\s,–-]+)$', line)
        if m:
            term, pages = m.group(1).strip(), m.group(2).strip()
            # clean ligatures
            term = term.replace('ﬁ', 'fi').replace('ﬂ', 'fl')
            index_items.append((term, pages))

# Comprehensive dictionary for Chinese translation of MML mathematical terms
term_map = {
    '1-of-K representation': '1-of-K 表示（独热表示）',
    'ℓ1 norm': 'ℓ1 范数',
    'ℓ2 norm': 'ℓ2 范数',
    'abduction': '溯因推理',
    'Abel-Ruffini theorem': '阿贝尔-鲁菲尼定理',
    'Abelian group': '阿贝尔群（交换群）',
    'absolutely homogeneous': '绝对齐次性',
    'activation function': '激活函数',
    'affine mapping': '仿射映射',
    'affine subspace': '仿射子空间',
    'Akaike information criterion': '赤池信息准则 (AIC)',
    'algebra': '代数',
    'algebraic multiplicity': '代数重数',
    'analytic': '解析的',
    'ancestral sampling': '祖先抽样',
    'angle': '夹角',
    'associativity': '结合律',
    'attribute': '属性',
    'augmented matrix': '增广矩阵',
    'auto-encoder': '自编码器',
    'basis': '基',
    'basis change': '基变换',
    'Bayes’ theorem': '贝叶斯定理',
    'Bayesian information criterion': '贝叶斯信息准则 (BIC)',
    'Bayesian linear regression': '贝叶斯线性回归',
    'Bernoulli distribution': '伯努利分布',
    'Bessel’s correction': '贝塞尔修正',
    'Beta distribution': 'Beta 分布',
    'bias': '偏置 / 偏差',
    'bias-variance tradeoff': '偏差-方差权衡',
    'bijection': '双射',
    'bilinear': '双线性的',
    'binary classification': '二元分类',
    'Binomial distribution': '二项分布',
    'block matrix': '分块矩阵',
    'box constraints': '盒约束',
    'canonical feature map': '典型特征映射',
    'Cauchy-Schwarz inequality': '柯西-施瓦茨不等式',
    'central limit theorem': '中心极限定理',
    'chain rule': '链式法则',
    'characteristic equation': '特征方程',
    'characteristic polynomial': '特征多项式',
    'Cholesky decomposition': 'Cholesky 分解',
    'classification': '分类',
    'closure': '封闭性',
    'coefficient matrix': '系数矩阵',
    'cofactor': '代数余子式',
    'column space': '列空间',
    'commutative': '可交换的',
    'commutativity': '交换律',
    'completing the square': '配方法',
    'composite function': '复合函数',
    'conditional distribution': '条件分布',
    'conditional probability': '条件概率',
    'conjugate prior': '共轭先验',
    'contour line': '等高线',
    'convex combination': '凸组合',
    'convex function': '凸函数',
    'convex hull': '凸包',
    'convex optimization': '凸优化',
    'convex set': '凸集',
    'coordinate': '坐标',
    'coordinate system': '坐标系',
    'correlation': '相关性',
    'covariance': '协方差',
    'covariance matrix': '协方差矩阵',
    'cross-validation': '交叉验证',
    'cumulative distribution function': '累积分布函数 (CDF)',
    'data covariance matrix': '数据协方差矩阵',
    'data point': '数据点',
    'data-fit term': '数据拟合项',
    'decoder': '解码器',
    'deep auto-encoder': '深度自编码器',
    'defective': '亏损的（不可对角化矩阵）',
    'denominator layout': '分母布局（矩阵微积分）',
    'derivative': '导数',
    'design matrix': '设计矩阵',
    'determinant': '行列式',
    'diagonal matrix': '对角矩阵',
    'diagonalizable': '可对角化的',
    'diagonalization': '对角化',
    'difference quotient': '差商',
    'dimension': '维度',
    'dimensionality reduction': '降维',
    'directed graphical model': '有向图模型',
    'direction': '方向',
    'direction space': '方向子空间',
    'distributive': '分配律',
    'dot product': '点积',
    'dual SVM': '对偶支持向量机',
    'duality': '对偶性',
    'dynamic programming': '动态规划',
    'eigengap': '特征间隙',
    'eigenspace': '特征子空间',
    'eigenvalue': '特征值',
    'eigenvector': '特征向量',
    'EM algorithm': 'EM 算法（期望最大化算法）',
    'empirical risk': '经验风险',
    'empirical risk minimization': '经验风险最小化 (ERM)',
    'encoder': '编码器',
    'entropy': '熵',
    'epigraph': '上图（Epigraph）',
    'epoch': '轮次 (Epoch)',
    'error function': '误差函数',
    'error term': '误差项',
    'estimate': '估计量 / 估计值',
    'estimator': '估计器',
    'Euclidean distance': '欧几里得距离',
    'Euclidean norm': '欧几里得范数',
    'Euclidean vector space': '欧几里得向量空间',
    'evidence': '证据（边际似然）',
    'evidence lower bound': '证据下界 (ELBO)',
    'expectation': '期望',
    'expectation maximization': '期望最大化 (EM)',
    'expected value': '期望值',
    'Fenchel conjugate': 'Fenchel 共轭',
    'Fisher discriminant': 'Fisher 判别',
    'Frobenius norm': 'Frobenius 范数',
    'Gaussian distribution': '高斯分布（正态分布）',
    'Gaussian mixture model': '高斯混合模型 (GMM)',
    'Gaussian process': '高斯过程 (GP)',
    'general linear group': '一般线性群',
    'generalized linear model': '广义线性模型 (GLM)',
    'generating set': '生成集',
    'geometric multiplicity': '几何重数',
    'global minimum': '全局极小值',
    'gradient': '梯度',
    'gradient descent': '梯度下降法',
    'Gram matrix': 'Gram 矩阵',
    'Gram-Schmidt orthogonalization': 'Gram-Schmidt 正交化',
    'group': '群',
    'hard margin': '硬间隔',
    'hard margin SVM': '硬间隔支持向量机',
    'Hessian': 'Hessian 矩阵（黑塞矩阵）',
    'Hilbert space': '希尔伯特空间',
    'hinge loss': '合页损失（Hinge Loss）',
    'hyperplane': '超平面',
    'hypothesis': '假设',
    'identity matrix': '单位矩阵',
    'iid': '独立同分布 (i.i.d.)',
    'ill-conditioned': '病态的（Ill-conditioned）',
    'image': '像空间 / 图像',
    'injective': '单射的',
    'inner product': '内积',
    'inner product space': '内积空间',
    'intercept': '截距',
    'inverse element': '逆元',
    'invertible': '可逆的',
    'isomorphism': '同构',
    'Jacobian': 'Jacobian 矩阵（雅可比矩阵）',
    'Jacobian determinant': '雅可比行列式',
    'Jensen’s inequality': 'Jensen 不等式',
    'joint probability': '联合概率',
    'Karush-Kuhn-Tucker': 'KKT 条件（Karush-Kuhn-Tucker 条件）',
    'kernel': '核 / 零空间 / 核函数',
    'kernel density estimation': '核密度估计 (KDE)',
    'kernel matrix': '核矩阵',
    'kernel PCA': '核主成分分析 (Kernel PCA)',
    'kernel trick': '核技巧',
    'Kullback-Leibler divergence': 'KL 散度（相对熵）',
    'label': '标签',
    'Lagrange multiplier': '拉格朗日乘子',
    'Lagrangian': '拉格朗日函数',
    'latent variable': '隐变量',
    'learning rate': '学习率',
    'least squares': '最小二乘法',
    'likelihood': '似然 / 似然函数',
    'linear combination': '线性组合',
    'linear mapping': '线性映射',
    'linear regression': '线性回归',
    'linearly dependent': '线性相关的',
    'linearly independent': '线性无关的',
    'linearly separable': '线性可分的',
    'logistic regression': '对数几率回归（逻辑回归）',
    'loss function': '损失函数',
    'manifold': '流形',
    'margin': '间隔',
    'marginal distribution': '边际分布',
    'marginal likelihood': '边际似然',
    'Markov random field': '马尔可夫随机场',
    'matrix': '矩阵',
    'maximum a posteriori': '最大后验估计 (MAP)',
    'maximum likelihood': '极大似然估计 (ML / MLE)',
    'mean': '均值',
    'metric': '度量',
    'mixture model': '混合模型',
    'mixture weight': '混合权重',
    'model selection': '模型选择',
    'multimodal': '多峰的',
    'multivariate': '多元的',
    'naive Bayes': '朴素贝叶斯',
    'negative log-likelihood': '负对数似然 (NLL)',
    'neural network': '神经网络',
    'Newton-Raphson': '牛顿-拉夫逊法（牛顿法）',
    'nonconvex': '非凸的',
    'norm': '范数',
    'normal distribution': '正态分布',
    'normal vector': '法向量',
    'null space': '零空间',
    'objective function': '目标函数',
    'orthogonal': '正交的',
    'orthogonal complement': '正交补',
    'orthogonal matrix': '正交矩阵',
    'orthogonal projection': '正交投影',
    'orthonormal': '标准正交的',
    'outlier': '离群点 / 异常值',
    'overfitting': '过拟合',
    'PageRank': 'PageRank 算法',
    'parameter estimation': '参数估计',
    'parameters': '参数',
    'partial derivative': '偏导数',
    'PCA': '主成分分析 (PCA)',
    'positive definite': '正定的',
    'positive semidefinite': '半正定的',
    'posterior': '后验 / 后验分布',
    'primal SVM': '原生支持向量机',
    'principal component': '主成分',
    'prior': '先验 / 先验分布',
    'probability density function': '概率密度函数 (PDF)',
    'projection': '投影',
    'quadratic form': '二次型',
    'quadratic program': '二次规划 (QP)',
    'radial basis function': '径向基函数 (RBF)',
    'random variable': '随机变量',
    'rank': '秩',
    'reconstruction error': '重构误差',
    'regularization': '正则化',
    'regularizer': '正则化项',
    'representer theorem': '表示定理',
    'reproducing kernel': '再生核',
    'ridge regression': '岭回归',
    'saddle point': '鞍点',
    'sample covariance': '样本协方差',
    'sample mean': '样本均值',
    'scalar': '标量',
    'sigmoid function': 'Sigmoid 函数',
    'singular value': '奇异值',
    'singular value decomposition': '奇异值分解 (SVD)',
    'slack variable': '松弛变量',
    'soft margin': '软间隔',
    'soft margin SVM': '软间隔支持向量机',
    'span': '张成（子空间）',
    'spectral theorem': '谱定理',
    'standard basis': '标准基',
    'standard deviation': '标准差',
    'stationary point': '驻点',
    'stochastic gradient descent': '随机梯度下降 (SGD)',
    'subgradient': '次梯度',
    'subspace': '子空间',
    'supervised learning': '监督学习',
    'support vector': '支持向量',
    'support vector machine': '支持向量机 (SVM)',
    'surjective': '满射的',
    'SVD': '奇异值分解 (SVD)',
    'Taylor series': '泰勒级数',
    'test error': '测试误差',
    'test set': '测试集',
    'Tikhonov regularization': 'Tikhonov 正则化（岭回归）',
    'trace': '迹',
    'training error': '训练误差',
    'training set': '训练集',
    'transformation matrix': '变换矩阵',
    'transpose': '转置',
    'triangle inequality': '三角不等式',
    'truncated SVD': '截断奇异值分解',
    'unbiased': '无偏的',
    'underfitting': '欠拟合',
    'unit vector': '单位向量',
    'unsupervised learning': '无监督学习',
    'variance': '方差',
    'vector': '向量',
    'vector field': '向量场',
    'vector space': '向量空间',
    'weight vector': '权重向量',
    'zero-one loss': '0-1 损失'
}

with open('4.Index.md', 'w', encoding='utf-8') as f:
    f.write('# 术语索引 (Index)\n\n')
    f.write('本书专业数学与机器学习核心术语中英双语对照及原书页码索引如下（按字母顺序排序）：\n\n')
    
    current_letter = ''
    for term, pages in index_items:
        first_char = term[0].upper()
        if not first_char.isalpha():
            first_char = '#'
        if first_char != current_letter:
            current_letter = first_char
            f.write(f'\n## {current_letter}\n\n')
            
        zh = term_map.get(term, '')
        if not zh:
            # try case-insensitive or stripped
            for k, v in term_map.items():
                if k.lower() == term.lower():
                    zh = v
                    break
                    
        if zh:
            f.write(f'- **{term}**（{zh}）, {pages}\n')
        else:
            f.write(f'- **{term}**, {pages}\n')

print(f'Wrote {len(index_items)} index items to 4.Index.md')
